version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
