default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool: 5
local:
  <<: *default
  database: myapp_development
development:
  <<: *default
  database: myapp_development



test:
  <<: *default
  database: myapp_test